# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-20 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumble_web.Place'),
        ),
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
